# Generated by Django 4.2.9 on 2024-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('facebook', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
