# Generated by Django 4.2.9 on 2024-02-05 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
